version: '3.9'

services:
  web:
    build: .
    image: 973050924786.dkr.ecr.us-west-2.amazonaws.com/personal-server:web
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/server/static
    env_file:
      - .env.staging
    expose:
      - 8000
  nginx-proxy:
    build: ./nginx
    image: 973050924786.dkr.ecr.us-west-2.amazonaws.com/personal-server:nginx
    ports:
      - 443:443
      - 80:80
    volumes:
      - static_volume:/home/app/server/static
      - certs:/etc/nginx/certs
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - web
    restart: always
  nginx-proxy-letsencrypt:
    image: jrcs/letsencrypt-nginx-proxy-companion
    env_file:
      - ./.env.staging.proxy-companion
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - certs:/etc/nginx/certs
      - html:/usr/share/nginx/html
      - vhost:/etc/nginx/vhost.d
      - acme:/etc/acme.sh
    depends_on:
      - nginx-proxy

volumes:
  static_volume:
  certs:
  html:
  vhost:
  acme: