version: '3.8'

services:
  personal-server:
    build: .
    volumes:
      - .:/django-server
    ports:
      - 8000:8000
    env_file:
      - ./.env
    container_name: server_container
    command: python manage.py runserver 0.0.0.0:8000