version: '3.8'

services:
  personal-server:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/django-server/staticfiles
    expose:
      - 8000
    env_file:
      - ./.env.prod
  ngnix:
    build: ./ngnix
    volumes:
      - static_volume:/home/app/django-server/staticfiles
    ports:
      - 1337:80
    depends_on:
      - personal-server

volumes:
  static_volume: