version: '3.9'

services:
  nginx:
    build: ./nginx
    ports:
      - 1300:80
    volumes:
      - static_volume:/home/app/server/static
    depends_on:
      - web
    restart: "on-failure"
  web:
    build: . #build the image for the web service from the dockerfile in parent directory
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/home/app/server/static
    env_file:
      - .env.staging
    image: server
    expose:
      - 8000:8000
    restart: "on-failure"

volumes:
  static_volume: