# Generated by Django 4.0.4 on 2023-01-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('profile_pic', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('resume', models.URLField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('github', models.URLField(blank=True, null=True)),
                ('linkedin', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('cover_image', models.URLField(blank=True, null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
    ]
